name: Deploy to Server

on:
  push:
    branches:
      - main
    paths:
      - "backend/src/**"
      - "backend/test/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths:
      - "backend/src/**"
      - "backend/test/**"
      - ".github/workflows/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh-keyscan -H ${{ secrets.SSH_SERVER_IP }} >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_SERVER_USER }}@${{ secrets.SSH_SERVER_IP }} << 'EOF'
            set -e
            cd /root/interview
            rm -rf share-profit-calculator  # Remove the directory if it exists
            # Clone the repo using the PAT stored in the GitHub secret
            git clone https://\${{ secrets.PAT }}:x-oauth-basic@github.com/StiliyanKushev/share-profit-calculator.git
            # Add any additional setup or deployment commands here
          EOF
