name: Run Backend e2e Tests

on:
  push:
    branches:
      - main
    paths:
      - "backend/src/**"
      - "backend/test/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths:
      - "backend/src/**"
      - "backend/test/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.8.0"

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          sudo systemctl start docker
          sudo docker --version
          sudo docker-compose --version

      - name: Install Dependencies
        run: npm ci
        working-directory: ./backend

      - name: Prepare .env
        run: cp .env.e2e .env
        working-directory: ./backend

      - name: Run Tests
        run: sudo npm run test:e2e
        working-directory: ./backend
