name: Run Backend Unit Tests

on:
  push:
    branches:
      - main
    paths:
      - "backend/src/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.8.0"

      - name: Install Dependencies
        run: npm ci
        working-directory: ./backend

      - name: Run Tests
        run: npm run test
        working-directory: ./backend
